version: "2"
services:
  gphoto_bot:
    container_name: gphoto_bot
    build:
      context: .
      dockerfile: Dockerfile.gphoto
    restart: on-failure
    ports:
      - "22000:22000"
    links:
      - postgres
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: gphoto
    ports:
      - "27018:5432"