version: "2"
services:
  gphoto_bot:
    container_name: gphoto_bot
    restart: on-failure
    build: .
    ports:
      - "22000:22000"
    links:
      - db
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: admin
      POSTGRES_DB: gphoto
    ports:
      - "27018:27017"